### ISSUE TITLE
ReportAbuseUrl returned by V2 and V3 feed is different

### ISSUE THREAD

**Issue by danliu** [NuGet/NuGetGallery#2476]
for V2 - it's https://www.nuget.org/Package/ReportAbuse/elmah/1.1.0

for V3 - it's https://www.nuget.org/packages/elmah/1.1.0/ReportAbuse

V3 is the correct URL that actually works, also the V2 URL is redirected to it. We should fix the V2 Url to return the right one.

**Comment by maartenba** [comment]
I believe this one was fixed in client? @xavierdecoster

**Comment by xavierdecoster** [comment]
@maartenba nope. Client added support for ReportAbuse template in index.json.
I'm still seeing hardcoded path in v2 server code: 

* V1: `siteRoot + "package/ReportAbuse/" + p.PackageRegistration.Id + "/" + p.Version` - https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/OData/PackageExtensions.cs#L45
* V2: `siteRoot + "package/ReportAbuse/" + p.PackageRegistration.Id + "/" + p.NormalizedVersion` - https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/OData/PackageExtensions.cs#L93

Those are *legacy routes*, configured here:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/App_Start/Routes.cs#L320

`Package/ReportAbuse/{id}/{version}` is redirected (permanently) to `packages/{id}/{version}/{action}`
