### ISSUE TITLE
Error: The package is invalid and cannot be uploaded. One or more files, such as '.rels' have a date in the future.

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3032]
_From @neurospeech on May 17, 2016 9:53_

This started only from today. 

I am in India, and I regularly publish NuGet Packages, till today everything was smooth. From today I started getting this error **The package is invalid and cannot be uploaded. One or more files, such as '.rels' have a date in the future.**.

I have tried both, command line publish as well as upload from the nuget.org website, but I get same error.

My clock is set to Indian Standard Time which is GMT+5.30, if I change my Timezone to GMT-6 CST, package can be uploaded successfully without any error. Your validation must consider UTC instead of localized timezone.

_Copied from original issue: NuGet/Home#2802_

**Comment by maartenba** [comment]
@neurospeech We are looking into this.

**Comment by maartenba** [comment]
We deployed an update to our services, the issue is now resolved.

**Comment by evanrobertson** [comment]
@maartenba I am still getting this error. Timezone is GMT+10

**Comment by maartenba** [comment]
Can you share the nupkg?

**Comment by evanrobertson** [comment]
Just having a look at it and the dates are being generated in the future. So I would assume this is an issue with the environment or cli tool.
[41stDegreeSoftware.FFImagePicker.1.0.7.nupkg.zip](https://github.com/NuGet/NuGetGallery/files/285800/41stDegreeSoftware.FFImagePicker.1.0.7.nupkg.zip)

**Comment by maartenba** [comment]
Which tool are you using? Can you share how the package is created?

**Comment by evanrobertson** [comment]
Using Mono 4.0.1, OSX 10.11.3
Then using `nuget pack *.nuspec`

**Comment by evanrobertson** [comment]
Nuget 3.4.3.855 seems to have resolved the issue

**Comment by ichernev** [comment]
@evanrobertson how did you update nuget with mono? I just downloaded mono and it came with nuget 2.8.5.0. I have OSX 10.11.5

**Comment by harikmenon** [comment]
try nuget update self

**Comment by ichernev** [comment]
@harikmenon thanks! I managed to use a newer version with brew. But 'time in future' error didn't go away with it. I did manage to upload the package from the command line though (error was only for uploading through the website). Also there were dates way back in the past, but nothing in the future.

**Comment by harikmenon** [comment]
Reopening issue. @maartenba : it looks like the Upload from website still has this issue? Can you investigate.

**Comment by maartenba** [comment]
Can you share the package that failed in the web UI with us?

**Comment by maartenba** [comment]
@ichernev Can you share the package that failed in the web UI with us so we can see why this error was happening?

**Comment by ichernev** [comment]
@maartenba it looks like the .nupkg file that was generated on both MacOS and Linux had dates of the files that are far in the future. Other than that there were no other issues.

**Comment by ichernev** [comment]
Also the command line let me upload a package without content folder, so I wouldn't say the web was to blame.

**Comment by maartenba** [comment]
Got it, thanks! Closing issue as the server rightfully blocked this package.

**Comment by veton** [comment]
Got the same issue publishing from CircleCI when using the latest nuget client awailable through apt-get.
**Environment:** https://github.com/veton/dotScript/blob/f3c03c6572903feaf3545007f44f3bba509ee6b8/build/Dockerfile
**CLI version:** 2.8.1.0
**Expected result:** package published successfully
**Actual Result:** Publish fails as per https://circleci.com/gh/veton/dotScript/4
