### ISSUE TITLE
Download count for package decreased between updates

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6069]
See https://github.com/NuGet/NuGetGallery/issues/6051

Download counts for `ical.net` (@rianjs) went from 228927 on 6/13 to 228832 on 6/14.

It's not clear whether or not this indicates we've lost data in the statistics DB or if a bug in the job that updates the Gallery DB with the latest download counts has an issue where it is incorrectly aggregating the results.

**Comment by skofman1** [comment]
@xavierdecoster , can you take a look? Any ideas?

**Comment by rianjs** [comment]
This was fixed with #6051

**Comment by scottbommarito** [comment]
@rianjs - although the download counts on your package have corrected themselves, we still don't know why download counts on your package between statistics updates decreased, so we need to investigate this and prevent it from happening in the future

**Comment by scottbommarito** [comment]
Duplicate of https://github.com/NuGet/NuGetGallery/issues/7053

(this was opened before that issue, but closing this one instead because the new issue is more detailed)
